name: Continious Integration

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: main

      # Install python and dependencies
      - name: Set up Python 3.11.7 and install dependencies
        run: |
          python3.11.7 -m pip install --upgrade pip
          pip install requests chardet pandas # Install the required libraries
        
      # Run CI
      - name: Continuous Integration
        run: |
         chmod u+r+x ./main/project/tests.sh
         cd ./main/project
         ./tests.sh
